# Generated by Django 2.2.5 on 2019-09-26 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Miasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miasto', models.CharField(max_length=25)),
                ('kod', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Uczelnia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=18)),
                ('nazwissko', models.CharField(max_length=20)),
                ('rok_studiow', models.CharField(max_length=10)),
                ('dochod', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_miasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mieszkancy', to='studenci.Miasto')),
                ('id_uczelni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studenci', to='studenci.Uczelnia')),
            ],
        ),
    ]
