# Generated by Django 2.2.5 on 2019-10-24 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studenci', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='miasto',
            options={'verbose_name_plural': 'miasta'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': 'studenci'},
        ),
        migrations.AlterModelOptions(
            name='uczelnia',
            options={'verbose_name_plural': 'uczelnie'},
        ),
        migrations.RemoveField(
            model_name='miasto',
            name='miasto',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id_miasta',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id_uczelni',
        ),
        migrations.RemoveField(
            model_name='student',
            name='nazwissko',
        ),
        migrations.RemoveField(
            model_name='student',
            name='rok_studiow',
        ),
        migrations.AddField(
            model_name='miasto',
            name='nazwa',
            field=models.CharField(default='Warszawa', max_length=30, verbose_name='miasto'),
        ),
        migrations.AddField(
            model_name='student',
            name='miasto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='studenci.Miasto'),
        ),
        migrations.AddField(
            model_name='student',
            name='nazwisko',
            field=models.CharField(default='Nowak', max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='roks',
            field=models.CharField(blank=True, default='', max_length=3, verbose_name='rok studiów'),
        ),
        migrations.AddField(
            model_name='student',
            name='uczelnia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='studenci.Uczelnia'),
        ),
        migrations.AlterField(
            model_name='miasto',
            name='kod',
            field=models.CharField(help_text='Wpisz kod pocztowy', max_length=6),
        ),
        migrations.AlterField(
            model_name='student',
            name='dochod',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='student',
            name='imie',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='uczelnia',
            name='nazwa',
            field=models.CharField(max_length=30, verbose_name='uczelnia'),
        ),
    ]
